# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a841dd84335239174a869725a902ec2a58ad12648b734597d073c0086c6244e4ab7a476938613d7ba64a99dfbcf11ec49f7b6cebb743bda12d26dbf4eee52e25

test:
  secret_key_base: 9342906b8abab67d4f6a8dce5b534d821d6794c635ee0e9d317416489f03a10b1ec749b8b0c6d2066813b9564a46652f470d0a094d89a91834b4c88c718c2f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
